spring:
  datasource:
    url: jdbc:mysql://localhost:3306/white_jotter?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 0909123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 热加载
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:/mapper/mybatis-config.xml
  # 实体扫描
  type-aliases-package: com.agan.wj.entity
  global-config:
    banner: false
    db-config:
      # 表名前缀
#      table-prefix: true
      # 自增
      id-type: auto



